# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cff47c56d17993bcc316b9353bf4c8f2967d46c9262987ec6d8b7ad6328a687c7ab333f6e5c42651fcaa3da363b33a25a0cc752085356f22ac01ae3246bb77c

test:
  secret_key_base: 813e4143f8903659c68568085bd62b5e8470d35f7f74975151f03f76cb9dda81175a45d7de860e03b9d6c349973a7b2b116144ad545162cb93a981a38de79885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
